language: go
go:
  - "1.10"

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/) # All the .go files, excluding vendor/
  - GOMETALINTER=https://github.com/alecthomas/gometalinter/releases/download/v2.0.5/gometalinter-2.0.5-linux-amd64.tar.gz
  - pushd $HOME && wget $GOMETALINTER && tar -xzvf *.tar.gz     # Linter

script:
  - gometalinter --install
  - gometalinter --help
  - gometalinter --disable-all --enable=errcheck --enable=vet --enable=vetshadow ./...
