language: go
go:
  - "1.10"

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/) # All the .go files, excluding vendor/
  - go get -u github.com/alecthomas/gometalinter                # Linter

script:
  - gometalinter --install
  - gometalinter --help
  - gometalinter --disable-all --enable=errcheck --enable=vet --enable=vetshadow ./...
