package irc

import (
	"bufio"
	"fmt"
	"strings"
)

// NumericCommand represents a numbered server reply
type NumericCommand int

//noinspection GoSnakeCaseUsage
const (
	RPL_WELCOME  NumericCommand = 001
	RPL_YOURHOST NumericCommand = 002
	RPL_CREATED  NumericCommand = 003

	RPL_MOTD      NumericCommand = 372
	RPL_MOTDSTART NumericCommand = 375
	RPL_ENDOFMOTD NumericCommand = 376

	ERR_UNKNOWNCOMMAND NumericCommand = 421
	ERR_NEEDMOREPARAMS NumericCommand = 461
)

// A NumericReply is a numbered reply generated by the server
type NumericReply struct {
	Code   NumericCommand
	Target string
	Params []string
}

func (n *NumericReply) ToMessage() *Message {
	params := []string{fmt.Sprintf("%03d", n.Code), fmt.Sprintf("%v", n.Target)}
	for _, p := range n.Params {
		params = append(params, p)
	}

	return &Message{
		Prefix: "tanya",
		Cmd:    NumericReplyCmd,
		Params: params,
	}
}

func (n *NumericReply) String() string {
	return n.ToMessage().String()
}

func (n *NumericReply) Error() string {
	return fmt.Sprintf("%03d: \"%v\"", n.Code, strings.Join(n.Params, "\",\""))
}

// MOTDAsNumerics formats a MOTD into a series of numeric replies.
func MOTDAsNumerics(target, motd string) []*NumericReply {
	var replies []*NumericReply

	scanner := bufio.NewScanner(strings.NewReader(motd))
	if scanner.Scan() {
		replies = append(replies, &NumericReply{
			Code:   RPL_MOTDSTART,
			Target: target,
			Params: []string{scanner.Text()},
		})
	}
	for scanner.Scan() {
		replies = append(replies, &NumericReply{
			Code:   RPL_MOTD,
			Target: target,
			Params: []string{scanner.Text()},
		})
	}
	replies = append(replies, &NumericReply{
		Code:   RPL_ENDOFMOTD,
		Target: target,
		Params: []string{"End of /MOTD command."},
	})
	return replies
}

// ErrUnknownCommand is the numeric reply to an unknown or invalid command
func ErrUnknownCommand(target, command string) *NumericReply {
	return &NumericReply{
		Code:   ERR_UNKNOWNCOMMAND,
		Target: target,
		Params: []string{command, "Unknown command"},
	}
}

// ErrNeedMoreParams is the numeric reply to a command that requires more params
func ErrNeedMoreParams(target, command string) *NumericReply {
	return &NumericReply{
		Code:   ERR_NEEDMOREPARAMS,
		Target: target,
		Params: []string{command, "Not enough parameters"},
	}
}
