name: Go
on:
  push:
    tags: [ v* ]
    branches: [ master ]
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v2.5.1
      with:
        version: v1.37.1
