name: Go
on:
  push:
    tags: [ v* ]
    branches: [ master ]
  pull_request:
  release:
    types: [ published ]
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v2.5.1
      with:
        version: v1.37.1
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Build
      run: go build -v -o tanya-${{runner.os}}
    - name: Test
      run: go test -v -race ./...
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: tanya-${{runner.os}}
        path: tanya-*
  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event.release.published
    steps:
    - name: Download binary artifacts
      uses: actions/download-artifact@v2
